### ISSUE TITLE
An error occurred connecting to Redis.

### ISSUE THREAD

**Issue by Thorakh** [colinmollenhour/Cm_Cache_Backend_Redis#1]
Hey Colin !

Firstly i wanna thank you for your awesome work on creating this new cache type.

Sometimes have got this error poping, particulary when traffic is high on the website :

An error occurred connecting to Redis.

Trace:
prod/.modman/Cm_Cache_Backend_Redis/lib/Credis/Client.php(278): Credis_Client->connect()
prod/.modman/Cm_Cache_Backend_Redis/Cm/Cache/Backend/Redis.php(128): Credis_Client->__call('hGet', Array)
prod/.modman/Cm_Cache_Backend_Redis/Cm/Cache/Backend/Redis.php(128): Credis_Client->hGet('zc:k:cc4_CORE_C...', 'd')
prod/lib/Zend/Cache/Core.php(303): Cm_Cache_Backend_Redis->load('cc4_CORE_CACHE_...', false)
prod/app/code/local/Mage/Core/Model/Cache.php(330): Zend_Cache_Core->load('CORE_CACHE_OPTI...')

for only 100 user connected on redis server.

What's your opinion ? 

Do you think this is somethink related with server configuration ? Have you ever experimented something like that ?

**Comment by luthirmasih** [comment]
FA DMD

**Comment by luthirmasih** [comment]
WA DUD
