### ISSUE TITLE
Issues clearing config cache

### ISSUE THREAD

**Issue by sander010587** [colinmollenhour/Cm_Cache_Backend_Redis#103]
Hello,

We are using the CM_Cache_Backend_Redis extension for over 1 year now on Magento 1.7.0.2 together with the sessions in Redis. Everything was working fine but if we now clear the config cache the server load increases to maximum and I have to restart php5-fpm in order to get things back to normal. This only happens when clearing the config cache. No errors in any log files to be found and the page loads correctly but just that right after clearing cache server load increases.

I already looked at the config cache corruption issue but applying the patch does not fix our problem. Also we did not receive the 100 router issues in our log so I think it is unrelated [Corruption bug](https://github.com/AmpersandHQ/magento-ce-ee-config-corruption-bug)

Any idea what might be causing this issue or how to debug? I already checked most of the XML files to see if any tags where missing but I believe everything is correct.

Thanks for any input on this. Site is working fine but it would be more convenient to not restart php5-fpm everytime the config cache is cleared.

Kind regards,

Sander

php 5.5.9
redis-cli 2.8.19
Magento 1.7.0.2

**Comment by colinmollenhour** [comment]
Magento has terrible config locking logic and what you are experiencing I believe is "stampeding". Try my modified version (I don't know for certain if it is 1.7 compatible).

https://gist.github.com/colinmollenhour/f7afefdf5b227f8cc677
