### ISSUE TITLE
Call to undefined function lzf_decompress() 

### ISSUE THREAD

**Issue by brentwpeterson** [colinmollenhour/Cm_Cache_Backend_Redis#104]
Getting following error intermittently :

 PHP Fatal error:  Call to undefined function lzf_decompress() in app/code/community/Cm/Cache/Backend/Redis.php on line 863

Running Magento 1.12 with PHP 5.5

**Comment by colinmollenhour** [comment]
No idea how that could be an intermittent error or how it would be the fault of the Redis.php code... The lzf module is a module so it is either enabled or not, right? Perhaps you have it enabled for apache/fcgi and not for CLI?

**Comment by brentwpeterson** [comment]
I think what we confirmed is that we have two servers Web and Admin. The admin server is the one that threw the error and it took down the frontend server. Rackspace first confirmed that lzf was loaded and then confirmed it wasn't so now we are testing.  I will post back to this ticket if it remains an issue but it seems it is solved.
