### ISSUE TITLE
Magento Enterprise..

### ISSUE THREAD

**Issue by brandontamm** [colinmollenhour/Cm_Cache_Backend_Redis#106]
I have the redis server setup and I enabled FPC in Magento config but 'magerun sys:check' shows that it isn't setup for FPC, sessions or backend cache.

Does Magento Enterprise come standard with Redis Full Page caching or would we install this extension?

Also, is there anywhere you can point me that would help a n00b start using Redis?

Thank you :)

**Comment by colinmollenhour** [comment]
Isn't this kind of question what Magento Enterprise is for? See #60.
