### ISSUE TITLE
Lost Connection to Redis Server

### ISSUE THREAD

**Issue by abhishek2244** [colinmollenhour/Cm_Cache_Backend_Redis#107]
Hello
 

I am facing a problem in which server keep showing me the message lost connection to redis server and when i refresh the page it is gone and it is happening frequently as you can see in the image in below link. Please help me resolve this issue.
(https://cloud.githubusercontent.com/assets/16360829/15625599/ab1a983e-24ca-11e6-97b0-609f23ca61a5.png)

**Comment by colinmollenhour** [comment]
How large is your config? To start eliminating issues you might try disabling Redis persistence in case it is an IO issue. Also try with/without phpredis, etc.

**Comment by abhishek2244** [comment]
Hey 
thanks for the support and disabling the redis persistence worked for me.

**Comment by colinmollenhour** [comment]
If you get that error due to Redis persistence feature then probably your disk is too heavy utilized or just too slow. You can keep it off but if you have to restart the Redis instance then you will start with an empty cache which may or may not be ok in your situation. Either way, I don't think there is anything to be done about it at the PHP layer since if the server is losing connections it is losing connections.. Cheers

**Comment by ravi2jdesign** [comment]
Hi Colin,

I am using redis but always having issue with redis, yet moment my current redis setting is "Cm_Cache_Backend_Redis" but I want to change this with "Cm_Cache_Backend_File"
so what config required for "Cm_Cache_Backend_File" 

Below are my current "Cm_Cache_Backend_Redis" config.
<full_page_cache>
            <lifetimelimit>86400</lifetimelimit>
            <backend>Cm_Cache_Backend_Redis</backend>
                <backend_options>
                    <server>172.25.211.251</server>
                    <port>6380</port>
                    <database>1</database>
                    <force_standalone>1</force_standalone>
        		<connect_retries>1</connect_retries>
                    <automatic_cleaning_factor>0</automatic_cleaning_factor>
                    <compress_data>0</compress_data>
                    <compress_tags>0</compress_tags>
                    <compress_threshold>20480</compress_threshold>
                    <compression_lib>gzip</compression_lib>
	            <read_timeout>15</read_timeout>
	            <timeout>5</timeout>
	            <lifetimelimit>43200</lifetimelimit>
                </backend_options>
        </full_page_cache>
Thanks
Ravi

**Comment by colinmollenhour** [comment]
The README includes examples: https://github.com/colinmollenhour/Cm_Cache_Backend_File
