### ISSUE TITLE
Strange problem with Redis and FPC and currencies 

### ISSUE THREAD

**Issue by postadelmaga** [colinmollenhour/Cm_Cache_Backend_Redis#114]
**Disclaimer:**  

This probably not the best place to post this issue since I am not 100% sure it is related to Redis, so feel free to close it in case you I am abusing this space 

--------------------------------------------------------------------------------------------------------------------------------------
My store is multi domain and every domain has a different default currency: 
 - .com -> USD 
 - .eu -> EUR

The store has `EE FPC` enabled on `Redis backend`.

**The issue**:  
Sometime product pages of the store `.com` get cached with a wrong currency. ( if I clean FPC then the page/currency it is ok )

Now FPC stores the key using the request and cookies ( so also the currency in case the user changed it) thus the key should be unique for every url/currency request.   
Anyway It looks like in some cases, request to product page X on the `Domain A`  override the cached page for the `Domain B`.

I cannot figure out what is the reason because this is happening on random basis and It is hard to reproduce.

What can I check ? any idea to debug this is very welcome

**Comment by colinmollenhour** [comment]
I would say this is not related to the backend and instead an application level bug. I don't even have access to EE source code so can't help you but it sounds like maybe there is an order of operations issue such as the cache key is built before the cookie is set on the first visit or something of that nature. Getting support for this kind of problem is why you pay for the EE license though, right?

**Comment by postadelmaga** [comment]
ok thanks for your feedback and the great work creating this backend :)

**Comment by postadelmaga** [comment]
by the way I find the issue.
I confirm it is not related to Redis but to the an inconsistent behavior of Magento Store obj and the EE FPC processor and how they manage the current currency value ( one use cookie the other the session )

For more details see: http://magento.stackexchange.com/questions/147482/fpc-issue-wrong-currency

**Comment by colinmollenhour** [comment]
Thanks for the update!
