### ISSUE TITLE
User account/session cross over

### ISSUE THREAD

**Issue by Carlewy** [colinmollenhour/Cm_Cache_Backend_Redis#12]
Hi Colin,
We've had a cross over occur at least once where a user on the Magento front end, ends up logged into another user's session (not on public computers, etc).  Has this been reported elsewhere by people utilising your Backend_Redis setup?

Tech details:
Magento multistore EE 1.11.1 on a single CentOS server, Apache, FastCGI, latest MySQL, Redis front and back, Phoenix Varnish cache

**Comment by chuckdrew** [comment]
Hi @Carlewy 

Did expanding the session hash sha512 fix the issue?

We are experiencing the same issue.

Thanks!

Chuck

**Comment by Carlewy** [comment]
Haven't used Magento in quite a while sorry.


Kind regards,
Darren Bell

**Comment by blackakula** [comment]
Hi @chuckdrew 

Any updates on this? We just faced with the same issue. Did above recommendations help you?

Regards,
Serhii

**Comment by cdrewidexx** [comment]
Sorry Serhil - I can't remember where we landed on this and I am not working on this project anymore. I don't think it will cause any harm to try it - but as Colin mentions, test it first...
