### ISSUE TITLE
1.10 ERR invalid password

### ISSUE THREAD

**Issue by luckyraul** [colinmollenhour/Cm_Cache_Backend_Redis#121]
after update to 1.10 
I got  
```
CredisException
ERR invalid password
```

With same config 1.9 works normally with password

**Comment by Xon** [comment]
Do you have a line number (or partial stack trace) associated with that error?

**Comment by luckyraul** [comment]
@Xon actually no

It was attempt to clear cache via n98

**Comment by luckyraul** [comment]
https://github.com/colinmollenhour/Cm_Cache_Backend_Redis/blob/master/Cm/Cache/Backend/Redis.php#L353

I guess this is it

**Comment by luckyraul** [comment]
check pull request for fix
