### ISSUE TITLE
Fatal Error after upgrade

### ISSUE THREAD

**Issue by gaiterjones** [colinmollenhour/Cm_Cache_Backend_Redis#127]
After a _modman update-all_ today I saw

`PHP Fatal error:  Arrays are not allowed in class constants in .modman/Cm_RedisSession/credis/Cluster.php on line 333`

And Magento was broken. I did a git reset --hard HEAD@{x} in .modman/Cm_Cache_Backend_Redis which resolved the problem. Is there a known issue with the latest updates?

Modman is managing :
Cm_RedisSession
Cm_Cache_Backend_Redis

**Comment by colinmollenhour** [comment]
Updated Credis to fix PHP <5.6  (1.9.1) and updated this repo to track it; released as 1.10.4.

Btw, you really should upgrade to PHP 7, it is sooo much faster.. :)

**Comment by gaiterjones** [comment]
Thanks, PHP 7 is not officially supported for Magento 1.x that's why I'm using it.

**Comment by colinmollenhour** [comment]
Any version of M1 can be made to work with PHP 7 quite easily such as by using https://github.com/Inchoo/Inchoo_PHP7
