### ISSUE TITLE
Remove all dependancies

### ISSUE THREAD

**Issue by woutersamaey** [colinmollenhour/Cm_Cache_Backend_Redis#144]
Why does this repo depend on `magento-hackathon/magento-composer-installer`?

I have been using this class for many years in simple Zend Framework projects, outside of Magento.

At first glance, this repo does not appear to have anything Magento related, so it should just work standalone or simply depend on `zf1/zend-cache`

**Comment by colinmollenhour** [comment]
Totally agreed.. I'm not a composer expert so I'm not sure what repercussions there would be for Magento users for removing it.. Maybe none?

**Comment by boldhedgehog** [comment]
`magento-hackathon/magento-composer-installer` was required for Magento 1, Magento 2 has it in some other `composer.json`, you can remove it from here.

**Comment by colinmollenhour** [comment]
I don't want to drop support for M1, but is it really "required" or should it perhaps just be "suggested"? An M1 project is going to already have `magento-hackathon/magento-composer-installer` as a dependency already, right?

**Comment by boldhedgehog** [comment]
I think making it suggested is fine.
I also think that Magento projects installing this package with Composer should have `magento-hackathon/magento-composer-installer` dependency alongside other packages installed with Composer.

**Comment by colinmollenhour** [comment]
Please see cecd07a. Looks good?

**Comment by colinmollenhour** [comment]
Also updated readme with mention of composer install.
