### ISSUE TITLE
Magento 1.7.0.2 and PHP 7.x

### ISSUE THREAD

**Issue by dandrikop** [colinmollenhour/Cm_Cache_Backend_Redis#146]
I have installed this extension on Magento 1.7.0.2 and it works fine. I'm conducting a feasibility study so as to determine the effort required to make Magento 1.7.0.2 run on PHP 7.x, so I would like to know if this extension supports PHP 7.0, 7.1 and 7.2.

**Comment by colinmollenhour** [comment]
Yes it works up to 7.2. Also, you might want to look at https://openmage.github.io/magento-lts/ which is tested up to 7.2.
