### ISSUE TITLE
Is it safe to have a single redis server handling cache, FPC and sessions?

### ISSUE THREAD

**Issue by tylerssn** [colinmollenhour/Cm_Cache_Backend_Redis#147]
Curious if we'd expect to run into connection limitations or if Magento's "Flush Cache Storage" and "Flush Magento Cache" execute a `flushall`

**Comment by colinmollenhour** [comment]
Main consideration is segmenting your storage so that one of the three cannot fill up your storage crippling the other two. In short, don't do it. Esp using Docker it is so easy to setup separate instances. There are no good reasons to do it and many reasons not to.
