### ISSUE TITLE
Robots.txt file is cached by REDIS Full Page Cache of Magento

### ISSUE THREAD

**Issue by dandrikop** [colinmollenhour/Cm_Cache_Backend_Redis#184]
When you change the contents of the robots.txt file via Content > Design > Configuration > Search Engine Robots, the changes do not become immediately available on the front-end of the Magento website even if you refresh the Configuration cache via System > Cache Management. It seems that the page https://www.example.com/robots.txt is cached by the Full Page Cache of Magento. I tested that on Magemto 2.4.6-p7 by using REDIS as the Full Page Cache of Magento.

The only way to make the changes of the robots.txt available at the front-end of the Magento website is by flushing the Full Page Cache. However, this work-around is not appropriate for the following reasons:

1. Robots.txt is considered configuration, and so any configuration change should become available immediately.
2. The Full Page Cache significantly improves the performance of the Magento front-end.
3. The Full Page Cache may need several days to be filled again even by using intensive Cache warmers.

So, it's worth flushing the Full Page Cache only when there are applied changes affecting a large number of pages, such as the installation of a new module, or the update of existing module.

Is there any way to either exclude some pages from getting stored in REDIS Full Page Cache, or clean only the REDIS keys associated with the robots.txt file?

**Comment by colinmollenhour** [comment]
I don't think this is a problem related to the Redis backend so this is not the proper place to report it. I.e., it would happen with the other backends as well. It is up to the app (Magento) to trigger invalidation at a granular level at the appropriate time, so please report this on magento/magento2.

> Is there any way to either exclude some pages from getting stored in REDIS Full Page Cache, or clean only the REDIS keys associated with the robots.txt file?

I'm not familiar enough with the Magento 2 FPC to know this, but I'm guessing the proper way to handle it is either a config backend model that clears the correct keys after config is saved, or adding the "config" tag to the cached page so it is cleared every time the config is updated.
