### ISSUE TITLE
Periodic 100% CPU usage on front-end servers

### ISSUE THREAD

**Issue by raptor75** [colinmollenhour/Cm_Cache_Backend_Redis#38]
Hi,

after deploying REDIS to the production servers, periodically at random times and unrelated to the load at that moment, the frontend servers end up using 100% CPU usage making the front-end unresponsive.

The site is set-up to have 3 app servers specifically for the frontend, and 1 app servers specifically for the backend admin. Sine the backend server is unaffected, I am thinking it is the FPC is cache-trashing.

Clearing or restarting REDIS has no effect. Restarting the zend services on the frontend servers seems to fix it. The unfortunate thing is this is not happening on the test environment (which is configured exactly the same).

Any help please? I cannot figure out what the issue could be. For the next steps I was going to switch off phpredis, and enable automatic cleaning factor, to see if it keeps happening, but of these will slow down the system.

Magento version is 1.9.0.0 EE
Redis version is 2.6.12
phpredis is installed on the app servers, latest from repository (2.2.3?)
lzf compression is installed
We set a cron job on the redis server that clears the cache completely using "redis-cli flushall" at 6am

Configuration on all 4 servers is the same
    &lt;cache&gt;
        &lt;backend&gt;Cm_Cache_Backend_Redis&lt;/backend&gt;
        &lt;backend_options&gt;
            &lt;server&gt;xxx.xxx.xxx.xxx&lt;/server&gt; &lt;!-- or absolute path to unix socket --&gt;
            &lt;port&gt;6379&lt;/port&gt;
            &lt;persistent&gt;cache-db0&lt;/persistent&gt; &lt;!-- Specify a unique string like "cache-db0" to enable persistent connections. --&gt;
            &lt;database&gt;0&lt;/database&gt;
            &lt;password&gt;&lt;/password&gt;
            &lt;force_standalone&gt;0&lt;/force_standalone&gt;  &lt;!-- 0 for phpredis, 1 for standalone PHP --&gt;
            &lt;connect_retries&gt;1&lt;/connect_retries&gt;    &lt;!-- Reduces errors due to random connection failures --&gt;
            &lt;read_timeout&gt;10&lt;/read_timeout&gt;         &lt;!-- Set read timeout duration --&gt;
            &lt;automatic_cleaning_factor&gt;0&lt;/automatic_cleaning_factor&gt; &lt;!-- Disabled by default --&gt;
            &lt;compress_data&gt;1&lt;/compress_data&gt;  &lt;!-- 0-9 for compression level, recommended: 0 or 1 --&gt;
            &lt;compress_tags&gt;1&lt;/compress_tags&gt;  &lt;!-- 0-9 for compression level, recommended: 0 or 1 --&gt;
            &lt;compress_threshold&gt;20480&lt;/compress_threshold&gt;  &lt;!-- Strings below this size will not be compressed --&gt;
            &lt;compression_lib&gt;lzf&lt;/compression_lib&gt; &lt;!-- Supports gzip, lzf and snappy --&gt;
        &lt;/backend_options&gt;
    &lt;/cache&gt;

Output of "info all" during a non-peak moment (now):
redis 127.0.0.1:6379> info all
# Server

redis_version:2.6.12
redis_git_sha1:00000000
redis_git_dirty:0
redis_mode:standalone
os:Linux 2.6.18-348.4.1.el5 x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.1.2
process_id:3566
run_id:f7ac169ac2700d731b359ef3cf86ac38e6602780
tcp_port:6379
uptime_in_seconds:147149
uptime_in_days:1
hz:10
lru_clock:707773
# Clients

connected_clients:25
client_longest_output_list:2
client_biggest_input_buf:0
blocked_clients:0
# Memory

used_memory:806210760
used_memory_human:768.86M
used_memory_rss:865255424
used_memory_peak:847086696
used_memory_peak_human:807.84M
used_memory_lua:31744
mem_fragmentation_ratio:1.07
mem_allocator:jemalloc-3.2.0
# Persistence

loading:0
rdb_changes_since_last_save:10793859
rdb_bgsave_in_progress:0
rdb_last_save_time:1370079388
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
# Stats

total_connections_received:278236
total_commands_processed:100407515
instantaneous_ops_per_sec:463
rejected_connections:0
expired_keys:176335
evicted_keys:0
keyspace_hits:63930946
keyspace_misses:2027440
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
# Replication

role:master
connected_slaves:0
# CPU

used_cpu_sys:1706.26
used_cpu_user:931.63
used_cpu_sys_children:0.00
used_cpu_user_children:0.00
# Commandstats

cmdstat_del:calls=407549,usec=3057946,usec_per_call=7.50
cmdstat_sadd:calls=32728843,usec=63358464,usec_per_call=1.94
cmdstat_srem:calls=389842,usec=842764,usec_per_call=2.16
cmdstat_sunion:calls=360857,usec=2499681,usec_per_call=6.93
cmdstat_hget:calls=65101268,usec=325685595,usec_per_call=5.00
cmdstat_hmset:calls=496261,usec=4722766,usec_per_call=9.52
cmdstat_select:calls=426630,usec=1788001,usec_per_call=4.19
cmdstat_expire:calls=496261,usec=1375386,usec_per_call=2.77
cmdstat_flushall:calls=2,usec=4346262,usec_per_call=2173131.00
cmdstat_info:calls=2,usec=566,usec_per_call=283.00
# Keyspace

db0:keys=19080,expires=14261

thanks,
Stefan

**Comment by jeroenvermeulen** [comment]
Thanks Colin, I think you saved my ass (again).

PS: I have created an extension which extends your caching extensions.
https://github.com/jeroenvermeulen/jeroenvermeulen-blockcache
It can:
- cache large blocks like the content area of category + product pages
- filter cache flushes by type, aka ignore certain flushes

**Comment by colinmollenhour** [comment]
Thanks for sharing @jeroenvermeulen. I am curious what the TTFB (TimeToFirstByte) is on a cache miss with the BlockCache extension?

If you haven't see it yet, check out Cm_Diehard, it is a Full Page Cache that supports real-time invalidation and has some really interesting properties.

**Comment by jeroenvermeulen** [comment]
TTFB is around 230ms for the homepage of https://www.any-lamp.com/

I checked out Cm_Diehard, I may give it a try on my next customer asking for full-page-cache.
I am also a contributor to Turpentine. Does Cm_Diehard fully support Varnish?

One other thing:
We had trouble at multiple customers with Cm_Cache_Backend_Redis. When we flush a large cache, for example 5 Gb, this flush takes 150 seconds. We have Lua enabled. During this 150s the shop frontend returned errors. 
I have created a workaround by extending your class and catching a lot of errors:
https://github.com/jeroenvermeulen/jeroenvermeulen-blockcache/blob/master/app/code/community/JeroenVermeulen/Cm/Cache/Backend/Redis.php

**Comment by colinmollenhour** [comment]
Cm_Diehard is designed to support lots of different backends and while it does include a Varnish VCL it is probably not production ready as I have not focused on Varnish at all. Also it needs a way to purge the upstream Varnish which should be easy (intended method is to implement an external script which watches a log file) but is not included currently.

IMO a 150 second lock is not acceptable and if this situation truly cannot be avoided (e.g. perhaps you can use more granular tags?) then I'd looks at using MongoDb backend instead as I think it will handle this much better.

**Comment by jeroenvermeulen** [comment]
Do you have plans for a Cm_Cache_Backend_Mongo? Would be nice!
The 150s lock is mainly when we flush BLOCK_HTML because we are releasing a new feature of fixed a bug occurring on many pages.

**Comment by colinmollenhour** [comment]
AFAIK it works perfectly already. I don't use it in production myself currently but it is unit tested and the code is quite simple thanks to Mongo's data model. If you have the server resources I'd give it a go. Note, you can't control MongoDb's memory usage so you will get the best results if it is on a dedicated machine. Definitely don't use it on a machine with your MySQL database unless you have tons of memory to spare.

**Comment by jeroenvermeulen** [comment]
Oops, I should have Googled "Cm_Cache_Backend_Mongo" first [shame].
Colin: You are great!
I will give it a go. My dedicated clients each run on a 128 Gb, 12C Xeon dedicated server, so that should not be a problem.
