### ISSUE TITLE
Prefix keys and tags

### ISSUE THREAD

**Issue by ArtemGoutsoul** [colinmollenhour/Cm_Cache_Backend_Redis#46]
Seems like a great class, but sometimes the same server setup is used for multiple applications, which means that in it's current form the class is not usable. It would be great to have support for a key/tag prefix. 

I. e. so that these prefixes:

``` php
const PREFIX_KEY      = 'zc:k:';
const PREFIX_TAG_IDS  = 'zc:ti:';
```

would actually be prefixed some an optional value fetched from configuration, e.g. named  "prefix".

**Comment by bery** [comment]
Opening an old issue, but just came across something interesting that is actually missing in the configuration example.

You should be able to use the built-in Magento cache prefix so you can protect multiple environments and/or applications in the same database like this
```xml
<config>
    <global>
        <cache>
            <backend>Mage_Cache_Backend_Redis</backend>
            <backend_options>
                <server>10.241.4.42</server> <!-- or absolute path to unix socket -->
                ..........
            </backend_options>
            <prefix>local_</prefix>
        </cache>
....
</global>
```
this produces something like

    zc:k:local_Zend_Locale

Note that the prefix is included in the key's name.

**Comment by colinmollenhour** [comment]
Read the discussion, the proper place to set the prefix is the frontend not the backend and the frontend already supports cache_id_prefix.

**Comment by elachino** [comment]
We had same problem using Lesti_FPC, and we resolved how say @bery, adding tag in fpc.xml file:

`<prefix>local_</prefix>`
