### ISSUE TITLE
composer vs. git submodules issue

### ISSUE THREAD

**Issue by SchumacherFM** [colinmollenhour/Cm_Cache_Backend_Redis#65]
hey,

composer does not support submodules as your modman app therefore the Credis lib folder will stay empty.

Any other solution except forking and copying the Credis class into the lib folder?
Also adding the Credis module to a projects root composer.json is not an option...

Thanks!

**Comment by yssource** [comment]
"post-update-cmd" do not git pull the lib/Credis if using the installer "Cotya/magento-composer-installer
".
it would be better to add the dependency as a composer dependency to their package. #https://github.com/Cotya/magento-composer-installer/issues/104

**Comment by colinmollenhour** [comment]
I am not familiar with composer enough to determine what is the best way for this issue to be resolved and don't have time to setup test environments and play around with it. It seems it would make sense for Cm_Cache_Backend_Redis to have a composer dependency on Credis, but I have yet to see a PR that solves the issue without breaking the original install method of using modman. I would love to merge a PR that does this though.

**Comment by colinmollenhour** [comment]
There was some good discussion over on #70 but it never was resolved, in case you hadn't seen that PR already.
