### ISSUE TITLE
Better divide cache and sessions

### ISSUE THREAD

**Issue by michelem09** [colinmollenhour/Cm_Cache_Backend_Redis#86]
Hi,
I was experiencing some connection issues with my Magento, I had this setup: 3 web servers in load balancing with 1 storage server (NFS) and 1 Redis server to handle cache and sessions.

I noticed that with this setup I had a lot of errors like "Connection to Redis failed after 2 failures", so I tried to divide the load of sessions and cache in 2 different redis servers and it seems connection errors have gone away.

Is it possible there is a problem keeping both your modules (cache, sessions) connected to the same redis instance (of course with different db #)? Did you have same complaints in past?

**Comment by craigcarnell** [comment]
Hi @michelem09 

In a production environment I have Magento connect to a cache instance on port 6379 and for sessions on port 6380 (so basically I have 2 redis instances running).

**Comment by michelem09** [comment]
So you are saying the same, the connection issues could happen more if cache and sessions are on the same redis instance.
I wanna try that too, now I tried with two completely different servers (one for cache, one for session), but I'd like to try with two redis instances on the same server.

**Comment by x86fantini** [comment]
we also run multiple instances of Redis on same server, with different
ports (6379, 6380, 6381, etc..) in this way we have different config files
and different memory allocation for each services and its working really
fine

2015-02-12 10:38 GMT+01:00 Michele Marcucci <notifications@github.com>:

**Comment by michelem09** [comment]
Thanks for feedbacks. I did the change and I put every redis instances in the same server and I still have the same good performance.
So I think it's definitely worth divide the load between several redis instances instead using the same for everything.

**Comment by x86fantini** [comment]
Redis is single thread. So multiples cores = multiple instances. Btw,
always use db "0" with credis library since now you have moved each service
in his own instances. We do the same and it's working like a charm

2015-02-12 13:03 GMT+01:00 Michele Marcucci <notifications@github.com>:
