### ISSUE TITLE
"Connection to Redis failed after 2 failures." Error in Magento  

### ISSUE THREAD

**Issue by brijesh07** [colinmollenhour/Cm_Cache_Backend_Redis#90]
I am using 1.9 and When i am Use catch code "Mage_Cache_Backend_Redis" in local.xml file
Code Like
![code](https://cloud.githubusercontent.com/assets/11854350/7067206/0f0326c0-dee7-11e4-8ab2-98d03f4a152c.PNG)
After Page Run error Like
![error](https://cloud.githubusercontent.com/assets/11854350/7067215/227d2692-dee7-11e4-9111-0963ab3c296b.PNG)
Please Provide Some solution

Thanks.
GitHub team

**Comment by colinmollenhour** [comment]
Github issues are not intended for technical support.

**Comment by Robx64** [comment]
Have you found a solution (2 years should be long enough to sort it out) :)??

**Comment by LukeHandle** [comment]
Sort what out? There is no pending issue here...
