### ISSUE TITLE
The redis database could not be selected.

### ISSUE THREAD

**Issue by woolkan** [colinmollenhour/Cm_Cache_Backend_Redis#94]
In Magento I get error 500 and in /var/report message "The redis database could not be selected.";i:1;s:1593:"#0 /home/www/lib/Cm/Cache/Backend/Redis.php(117): Zend_Cache::throwException('The redis datab...').

Could you help me to find solution for this problem?

**Comment by colinmollenhour** [comment]
Make sure the redis config has specified the correct number of databases and confirm that the command works with redis-cli.
